### ISSUE TITLE
Curious if you have any plans to update this.

### ISSUE THREAD

**Issue by mdsitton** [almossawi/firefox-codebase-evolution#1]
Found the article and tool quite interesting but there have been 24 firefox releases since this was initially done. So it would certainly be interesting to see how the trends continued evolving in the releases since. If not feel free to close this, Thanks.

**Comment by almossawi** [comment]
Yes, you can find the current iteration of this work [in this repo](https://github.com/mozilla/firefox-code-quality) and the demo [here](https://metrics.mozilla.com/code-quality/).

I'll be pushing an update on Monday that adds data for revisions for the past 10 years or so.

**Comment by mdsitton** [comment]
Thanks, should be interesting.
